#! /bin/sh

setxkbmap latam &
xrandr -s 1920x1080 &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5
#I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Thunar desktop='^3' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# POLYBAR
~/.config/polybar/launch.sh

# Wallpaper
feh --bg-fill ~/Wallpaper/neon.png &

# Picom
#picom &
